### ISSUE TITLE
URLs are double encoded

### ISSUE THREAD

**Issue by Tommybearrr** [louislewis2/payfast#11] opened 2019-05-13 14:41 UTC
Hello

After updating to version 1.0.4 to work with the latest JSON, I am now receiving double encoded string from the PayfastRequest.ToString();
E.g. https://xxxxxxxxx.com becomes https%3A%2F%2xxxxxxxxx.com.

Let me know if you need anymore information.
Thanks for the great lib.

**Comment by louislewis2** [comment] 2019-05-14 04:03
Hi, thanks for the report. I will take a look and try reproduce locally and will also check out your pr. Let you know soon. Thanks

**Comment by 4saken07** [comment] 2019-07-17 23:56
Hi

@Tommybearrr PayFast calculates the MD5 hash from the encoded string (eg. https%3A%2F%2xxxxxxxxx.com) and this is why the signature doesn't work on your Pull Request (because you have removed the encoding and are calculating the MD5 hash on a plaintext URL which is not the same as PayFast). 

I have integrated the latest version just fine (1.0.4). PayFast doesn't care that the URLs are encoded, and the return urls (accept/cancel/notify) work fine.

**Comment by louislewis2** [comment] 2019-07-22 19:49
Thanks @4saken07, can I close this issue?

**Comment by 4saken07** [comment] 2019-07-29 12:10
@louislewis2 I don't see why not, I integrated the code just fine. It works perfectly. Thank you for the library, I had to write all this stuff manually when I did this in PHP, this has saved me a lot of time!

**Comment by louislewis2** [comment] 2019-07-31 17:53
@4saken07 Thanks for the kind words, happy it helped you out.

**Closed as completed by louislewis2** 2019-07-31 17:53 UTC

**Comment by Tommybearrr** [comment] 2019-08-01 08:34
Sorry the delayed responsive as I have been traveling. 
The double encoded issue was by payfast when I could not get it to work. 
But I have changed it in my fork to get the signature from the encoded string and pass the plain URL to Payfast.

Thanks for all your help guys.
